### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by psolymos** [psolymos/qpad-book#1]
- [ ] Update content with bSims & detect & data sets (paired, lhreg)
- [ ] renv based project setup
- [ ] add gh action for deployment
- [ ] Update slides, Rmd
- [ ] Add learnr tutorials
- [ ] Use pagedown/pagedreport to generate pdf output
